version: '2'
services:
  web:
    image: vulhub/cmsms:2.2.9.1
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=cmsms
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - cmsms-network

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cmsms
    networks:
      - cmsms-network

networks:
  cmsms-network:
    driver: bridge

