apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: cmsms
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_USER
              value: root
          image: vulhub/cmsms:2.2.9.1
          name: web
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
